theme_version: 1.0.1

# Site settings
title:              Eveline Vondeling
logo:               # Logo image URL
description:        Haptic Art Curator
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://evelinevondeling.com/' # The base hostname & protocol for your site
linkedin:           'https://twitter.com/aspirethemes'
facebook:           'https://www.facebook.com/aspirethemes'
instagram:          'https://www.instagram.com/aspirethemes'

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext